FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod tidy && CGO_ENABLED=0 go build -ldflags="-s -w" -o api ./cmd/api/

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/api .
EXPOSE 5004
CMD ["./api"]
