version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-nodejs
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=orders_db
    ports:
      - "5002:5002"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nodejs-net
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: db-nodejs
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata_nodejs:/var/lib/postgresql/data
      - ../shared/db-init:/docker-entrypoint-initdb.d:ro
    networks:
      - nodejs-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata_nodejs:

networks:
  nodejs-net:
    driver: bridge
